// src/pages/index.tsx
import { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className="min-h-screen bg-gray-100 flex items-center justify-center">
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-4 bg-white rounded-lg shadow-md">
        <h1 className="text-4xl font-bold text-center mb-4">Welcome to My Next.js App</h1>
        <p className="text-center text-lg">
          This is a simple starter page for a Next.js application using TypeScript and Tailwind CSS.
        </p>
      </main>
    </div>
  );
};

export default Home;
